### ISSUE TITLE
'modals.less' wasn't found.

### ISSUE THREAD

**Issue by rugk** [imgbi/img.bi#58]
```
$ ./cli.js
INFO: Building static content
INFO: [XX:YY:ZZ] 
INFO: Working directory changed to ~/node/node_modules/img.bi-server

INFO: [XX:YY:ZZ] 
INFO: Using gulpfile ~/node/node_modules/img.bi-server/gulpfile.js

INFO: [XX:YY:ZZ] 
INFO: Starting 'css'...

INFO: [XX:YY:ZZ] 
INFO: Starting 'js'...

INFO: [XX:YY:ZZ] 
INFO: Starting 'html'...

INFO: [XX:YY:ZZ] 
INFO: Starting 'favicons'...

INFO: [XX:YY:ZZ] 
INFO: Starting 'fonts'...

events.js:159
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (Potentially unhandled rejection [2] 'modals.less' wasn't found. Tried - /.../node_modules/img.bi-server/frontend/less/modals.less,node_modules/bootstrap/less/modals.less,frontend/less/modals.less,modals.less in file /.../node_modules/img.bi-server/frontend/less/main.less line no. 29
)
    at GulpRunner.emit (events.js:157:17)
    at Socket.<anonymous> (/.../node_modules/gulp-runner/index.js:59:10)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:534:20)
```

When [uncommenting this line](https://github.com/imgbi/img.bi/blob/98e56a70fb664b38d1a96e9614d792fa09e03f69/frontend/less/main.less#L29) I get another error:
```
Error: Uncaught, unspecified "error" event. (Potentially unhandled rejection [2] 'responsive-utilities.less' wasn't found. Tried - /.../node_modules/img.bi-server/frontend/less/responsive-utilities.less,node_modules/bootstrap/less/responsive-utilities.less,frontend/less/responsive-utilities.less,responsive-utilities.less in file /.../node_modules/img.bi-server/frontend/less/main.less line no. 26
)
    at GulpRunner.emit (events.js:157:17)
    at Socket.<anonymous> (/.../node_modules/gulp-runner/index.js:59:10)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at Pipe.onread (net.js:534:20)
```

**Comment by rugk** [comment]
BTW these warnings were shown when installing:
```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@1.11.0: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
```

**Comment by rugk** [comment]
Okay, I've now cloned the latest version directly from GitHub and it worked...
